### ISSUE TITLE
The print statements don't match the files and LCA's

### ISSUE THREAD

**Issue by JonMGabriel** [jcampanelli/LCA-Project#13]
Just noticed this while I was running the algorithms with the new commits on Liz and Julie. The runtime print statements don't match the algorithms that the file was named after. I'm pretty sure the names of the files are just backwards, but i'm confused at how this even happened. One is intended for C and the other C++...so, wat? Just wanted to point this out.

**Comment by lisanketcham** [comment]
YOU'RE RIGHT! The one intended for C is 2 and 4. The one intended for C++ is 1 and 3. The print statements are correct, the file names are switched. I'm so sorry, this is definitely my fault.

**Comment by JonMGabriel** [comment]
It's all good. I just was making sure that didn't mess anyone else up. I'll just edit the file names for the machines liz and julie, I'll close this issue now.
